# Global Values
repoUrl: 'https://github.com/aws-samples/eks-blueprints-add-ons.git'
targetRevision: HEAD
region: ''
account: ''
clusterName: ''
destinationServer: ''
argoNamespace: ''
argoProject: ''

# Agones Values
agones: 
  enable: false 
  createNamespace: true

# App Mesh Values
appMesh: 
  enable: false 
  createNamespace: true

# Calico Values
calico:
  enable: false

# AWS CloudWatch Metrics Values
awsCloudWatchMetrics:
  enable: false
  createNamespace: true
  serviceAccountName:

# AWS EFS CSI Driver Values
awsEfsCsiDriver:
  enable: false
  serviceAccountName:

# AWS for Fluent Bit Values
awsForFluentBit:
  enable: false
  createNamespace: true
  logGroupName:
  serviceAccountName:

# AWS Load Balancer Controller Values
awsLoadBalancerController:
  enable: false
  createNamespace: true
  serviceAccountName:
  podDisruptionBudget:
    maxUnavailable: 1
  respectIgnoreDifferences: true
  ignoreDifferences:
  - group: ""
    kind: "Secret"
    jsonPointers:
    - /data
  - group: "admissionregistration.k8s.io"
    kind: "MutatingWebhookConfiguration"
    jqPathExpressions:
    - '.webhooks[]?.clientConfig.caBundle'
  - group: "admissionregistration.k8s.io"
    kind: "ValidatingWebhookConfiguration"
    jqPathExpressions:
    - '.webhooks[]?.clientConfig.caBundle'

# AWS Node Termination Handler Values
awsNodeTerminationHandler:
  enable: false
  serviceAccountName:

# AWS Otel Collector Values
awsOtelCollector:
  enable: false
  createNamespace: true
  otlpEndpoint:
  resourceAttributes:

# Cert Manager Values
certManager:
  enable: false
  createNamespace: true
  serviceAccountName:

# Cert Manager CSI Driver Values
certManagerCsiDriver:
  enable: false

# Cluster Autoscaler Values
clusterAutoscaler:
  enable: false
  serviceAccountName:

# Datadog Operator
datadogOperator:
  enable: false

# Strimzi Kafka Operator
strimziKafkaOperator:
  enable: false

# Strimzi Topic Operator
strimziTopicOperator:
  enable: false

# Loki distributed
lokiDistributed:
  enable: false
  serviceAccount:
    create: false
  storageS3:
    enable: false
    region: "us-east-1" # default
    bucketName:

# External DNS Values
externalDns:
  enable: false
  createNamespace: true
  serviceAccountName:
  zoneIdFilter:

# External Secrets Operator
externalSecrets:
  enable: false

# Gatekeeper Values
gatekeeper:
  enable: false
  createNamespace: true
  clusterName:

# Nginx Values
ingressNginx:
  enable: false
  createNamespace: true

# Grafana default Values
grafana:
  enable: false
  serviceAccount:
    create: false

# Vault default Values
vault:
  enable: false

# Karpenter Values
karpenter:
  enable: false
  createNamespace: true
  serviceAccountName:
  controllerClusterEndpoint:
  awsDefaultInstanceProfile:
  interruptionQueueName:
  ignoreDifferences:
  - group: ""
    kind: "Secret"
    jsonPointers:
    - /data

# Keda Values
keda:
  enable: false
  createNamespace: true
  serviceAccountName:

# Metrics Server Values
metricsServer:
  enable: false

# Ondat Values
ondat:
  enable: false
  createNamespace: true
  etcdClusterCreate: false
  serviceAccountName:
  clusterSecretRefName:
  clusterAdminUsername:
  clusterAdminPassword:
  clusterKvBackendAddress:
  clusterKvBackendTLSSecretName:
  clusterKvBackendTLSSecretNamespace:
  clusterNodeSelectorTermKey:
  clusterNodeSelectorTermValue:
  etcdNodeSelectorTermKey:
  etcdNodeSelectorTermValue:
  etcdClusterReplicas:
  etcdClusterStorageclass:
  etcdClusterStorage:

# Prometheus Values
prometheus:
  enable: false
  createNamespace: true
  serviceAccountName:
  roleArn:
  ampWorkspaceUrl:
  nodeExporter:
    enabled: false
  kubeStateMetrics:
    enabled: false
  alertmanager:
    enabled: false
  pushgateway:
    enabled: false
  serverFiles:
    alerting_rules.yml: {}
    alerts: {}
    recording_rules.yml: {}
    rules: {}
    prometheus.yml:
      rule_files:
        - /etc/config/recording_rules.yml
      scrape_configs:
        - job_name: prometheus
          static_configs:
            - targets:
              - localhost:9090
        - job_name: 'kubernetes-nodes'
          scheme: https
          tls_config:
            ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
            insecure_skip_verify: true
          bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
          kubernetes_sd_configs:
            - role: node
          relabel_configs:
            - action: labelmap
              regex: __meta_kubernetes_node_label_(.+)
            - target_label: __address__
              replacement: kubernetes.default.svc:443
            - source_labels: [__meta_kubernetes_node_name]
              regex: (.+)
              target_label: __metrics_path__
              replacement: /api/v1/nodes/$1/proxy/metrics
        - job_name: 'kubernetes-pods'
          honor_labels: true
          kubernetes_sd_configs:
            - role: pod
          relabel_configs:
            - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
              action: keep
              regex: true
            - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape_slow]
              action: drop
              regex: true
            - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scheme]
              action: replace
              regex: (https?)
              target_label: __scheme__
            - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
              action: replace
              target_label: __metrics_path__
              regex: (.+)
            - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_port, __meta_kubernetes_pod_ip]
              action: replace
              regex: (\d+);(([A-Fa-f0-9]{1,4}::?){1,7}[A-Fa-f0-9]{1,4})
              replacement: '[$2]:$1'
              target_label: __address__
            - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_port, __meta_kubernetes_pod_ip]
              action: replace
              regex: (\d+);((([0-9]+?)(\.|$)){4})
              replacement: $2:$1
              target_label: __address__
            - action: labelmap
              regex: __meta_kubernetes_pod_annotation_prometheus_io_param_(.+)
              replacement: __param_$1
            - action: labelmap
              regex: __meta_kubernetes_pod_label_(.+)
            - source_labels: [__meta_kubernetes_namespace]
              action: replace
              target_label: namespace
            - source_labels: [__meta_kubernetes_pod_name]
              action: replace
              target_label: pod
            - source_labels: [__meta_kubernetes_pod_phase]
              regex: Pending|Succeeded|Failed|Completed
              action: drop

# Metrics Server Values
sparkOperator:
  enable: false
  createNamespace: true

# Tetrate Istio Values
tetrateIstio:
  enable: false
  createNamespace: true
  base:
  cni:
  istiod:
  global:

# Thanos Values
thanos:
  enable: false

# Traefik Values
traefik:
  enable: false
  createNamespace: true

# VPA Values
vpa:
  enable: false
  createNamespace: true

# Yunikorn Values
yunikorn:
  enable: false
  createNamespace: true

# Argo Rollout Values
argoRollouts:
  enable: false
  createNamespace: true

# Argo Rollout Values
argoWorkflows:
  enable: false

# Kube State Metrics Values
kubeStateMetrics:
  enable: false
  createNamespace: true
  serviceAccountName:

# Prometheus Node Exporter
promtheusNodeExporter:
  enable: false
  serviceAccountName:
  
# Kubernetes Dashboard Values
kubernetesDashboard:
  enable: false
  serviceAccountName:

# promtail Values
promtail:
  enable: false

# kubecost Values
kubecost:
  enable: false

# SMB CSI Driver Values
smbCsiDriver:
  enable: false

# Chaos Mesh Values
chaosMesh:
  enable: false

# Cilium Mesh Values
cilium:
  enable: false

# Reloader Values
reloader:
  enable: false

# Kube Prometheus Stack
kubePrometheusStack:
  enable: false

# Kyverno Values
kyverno:
  enable: false

policies:
  enable: false

reporter:
  enable: false

# NVIDIA Device Plugin Values
nvidiaDevicePlugin:
  enable: false

# Consul Values
consul:
  enable: false
  
velero:
  enable: false

opentelemetryCollector:
  enable: false
  serviceAccountName:
